### ISSUE TITLE
Error sending confirmation emails

### ISSUE THREAD

**Issue by gjm76** [NNTmux/newznab-tmux#1088]
Whenever a user registers the site comes up with error 500 (on the dev version) and the email doesnt get sent even though corrent smtp info is in .env.

in laravel telescope i see this error ;

Swift_TransportException
Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients "

**Comment by DariusIII** [comment]
Message is self explanatory, email address of the recipient is not valid.

**Comment by gjm76** [comment]
Sorry i should have explained better, this happens whenever a user account tries to register, they get a errror 500 and thats whats in laravell telescope each time. I have tried registering as a new user and same thing happens

**Comment by DariusIII** [comment]
Paste here the stack trace from telescope.

**Comment by gjm76** [comment]
/var/www/NNTmux/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:341
/var/www/NNTmux/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php:305
/var/www/NNTmux/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:390
/var/www/NNTmux/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:497
/var/www/NNTmux/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:516
/var/www/NNTmux/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:206
/var/www/NNTmux/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php:71
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:486
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:261
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php:159
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php:19
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php:160
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:277
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:231
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php:122
/var/www/NNTmux/app/Jobs/SendNewRegisteredAccountMail.php:40
:
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Util.php:36
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:90
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:34
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Container.php:590
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:94
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:130
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:105
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:98
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:83
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:130
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:105
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:85
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:59
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php:88
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php:45
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:44
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:177
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:160
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:73
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php:112
/var/www/NNTmux/app/Observers/UserServiceObserver.php:39
:
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:388
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:218
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php:188
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:825
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:667
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:765
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Support/helpers.php:422
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:766
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:23
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1620
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1632
/var/www/NNTmux/app/Http/Controllers/Auth/RegisterController.php:76
/var/www/NNTmux/app/Http/Controllers/Auth/RegisterController.php:178
:
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Routing/Route.php:219
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Routing/Route.php:176
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Routing/Router.php:681
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:130
/var/www/NNTmux/app/Http/Middleware/RedirectIfAuthenticated.php:24
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/var/www/NNTmux/vendor/pragmarx/firewall/src/Middleware/FilterMiddleware.php:32
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:76
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php:39
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:56
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:66
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:105
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Routing/Router.php:683
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Routing/Router.php:658
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Routing/Router.php:624
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Routing/Router.php:613
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:170
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:130
/var/www/NNTmux/vendor/genealabs/laravel-caffeine/src/Http/Middleware/LaravelCaffeineDripMiddleware.php:11
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/var/www/NNTmux/vendor/fideloper/proxy/src/TrustProxies.php:57
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:63
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:105
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:145
/var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:110
/var/www/NNTmux/public/index.php:7

**Comment by DariusIII** [comment]
> Sorry i should have explained better, this happens whenever a user account tries to register, they get a errror 500 and thats whats in laravell telescope each time. I have tried registering as a new user and same thing happens

What email address was used? "No valid recipient" is pretty self explanatory error. You must use valid email addresses in NNTmux, temporary ones, one-time-use ones are blocked.

**Comment by gjm76** [comment]
for the person signing up, any lol, i tried gmail, outlook, my work email, my personal email, my friend tried his work and person email still error 500 and that same exception.

as said im on the develop branch, would i be better on the master ?

**Comment by DariusIII** [comment]
No, no, dev is where all the fun is :)
I have pushed a change to dev, requested by you, so you can verify your users with one click :)

**Comment by gjm76** [comment]
thanks, other things ive noticed are send to downloader not working, trying to connect to api doesnt work , are these known bugs?.

Also seem to get a error 500 as soon as i login and resubmitting info lets me in, error in telescope says something about tagging not supported in cache? .

Still cant see why this email problem is happening, maybe you try registering on mine?

**Comment by gjm76** [comment]
and to update, is it just a git pull or would i need to do something else?

**Comment by DariusIII** [comment]
php artisan nntmux:all

How does connecting to API not work? 
And please check all of your folder permissions.

**Comment by gjm76** [comment]
getting this error when running that
Getting changes from Github
Command 'git 'pull' 'origin' 'dev' '--tags'' failed (exit-code 1).
The Smarty compiled template cache has been cleaned for you

and api just doesnt connect for some reason

**Comment by gjm76** [comment]
ok sorted that issue but now theres a issue, i cant login as admin user anymore, i get error 500's since that update

**Comment by gjm76** [comment]
this is what happened when i updated ;

nntmux@Nntmux:/var/www/NNTmux$ php artisan nntmux:all
Application is now in maintenance mode.
Getting changes from Github
Already up to date.
Running composer install process...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
PHP Warning:  file_put_contents(/var/www/NNTmux/.git/hooks/pre-commit): failed to open stream: No such file or directory in /var/www/NNTmux/vendor/captainhook/captainhook/src/Storage/File.php on line 87
PHP Warning:  chmod(): No such file or directory in /var/www/NNTmux/vendor/captainhook/captainhook/src/Runner/Installer.php on line 289
> Blacklight\build\ComposerScripts::postInstall
> Blacklight\build\ComposerScripts::postInstallCmd
sh: 1: build/git-hooks/addHooks.sh: not found
Updating database
Nothing to migrate.
The Smarty compiled template cache has been cleaned for you
Application is now live.
nntmux@Nntmux:/var/www/NNTmux$

**Comment by gjm76** [comment]
2020/02/27 03:59:28 [error] 12438#12438: *49362 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/NNTmux/storage/framework/views/739b44a4e87f7ca585319a033c8954ea1ab53937.php): failed to open stream: Permission denied in /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/NNTmux...', 133, Array)
#1 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents('/var/www/NNTmux...', '<?php $__env->s...', 0)
#2 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(129): Illuminate\Filesystem\Filesystem->put('/var/www/NNTmux...', '<?php $__env->s...')
#3 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile('/var/www/NNTmux...')
#4 /var/www/NNTmux/vendor/facade/ignition/src/Views/Engines/" while reading response header from upstream, client: 86.143.156.75, server: nzb.life, request: "POST /login HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "nzb.life", referrer: "http://nzb.life/login"
nntmux@Nntmux:/var/www/NNTmux$


not sure why its permission denied as anything should be able to write there 

nntmux@Nntmux:/var/www/NNTmux/storage/framework/views$ ls -lsir
total 64
229379054  4 -rwxrwxrwx 1 nntmux www-data  1038 Feb 19 20:21 f8c22adf98de4fc20a1e9c8b3dbaed04bc36753b.php
229379042  4 -rwxrwxrwx 1 nntmux www-data   586 Feb 19 21:59 db5c293e3b19db1f1ed5ef404ac4ce5e1b8b540b.php
229379032  4 -rwxrwxrwx 1 nntmux www-data  1067 Feb 19 16:08 daa8ea92ec8b9d524753eda1f48c80b3cb8f2da2.php
229379053  4 -rwxrwxrwx 1 nntmux www-data   461 Feb 19 20:21 d5d58fc9815ec0f802ebf0cd7bf2dace66cbe5ef.php
229379021  8 -rwxrwxrwx 1 nntmux www-data  6173 Feb 19 21:07 c024263922a7a1879f1931a4546ce61b461af557.php
229379000  4 -rwxrwxrwx 1 nntmux www-data  2824 Feb 19 15:05 b6e0ef998257bdedbf2f6c87020665170958339e.php
229378983  4 -rwxrwxrwx 1 nntmux www-data   425 Feb 27 04:06 739b44a4e87f7ca585319a033c8954ea1ab53937.php
229379031  4 -rwxrwxrwx 1 nntmux www-data   502 Feb 19 16:08 60ecd3d576b7845f9d9b2121417590452724bf22.php
229379001 16 -rwxrwxrwx 1 nntmux www-data 14697 Feb 19 21:06 5c8bdf5e164ba15888b9dfb9280125c3216138ea.php
229379020  4 -rwxrwxrwx 1 nntmux www-data  1186 Feb 19 21:06 1a8c4269445f420db918f0fb1789b359238d2d39.php
229378608  4 -rwxrwxrwx 1 nntmux www-data   756 Feb 27 03:42 16d69e752561d230dccaf2b7aec4854ec3a4ca7f.php
229378984  4 -rwxrwxrwx 1 nntmux www-data  1795 Feb 27 04:06 0b7fef642de13fbbadfe5a125c96d44dd06d06d8.php
nntmux@Nntmux:/var/www/NNTmux/storage/framework/views$

All was ok until i did the update?

**Comment by DariusIII** [comment]
Just give it a 777 perm. Something must have been changed inside framework itself, that triggered permission issues on your end.

**Comment by gjm76** [comment]
still same issue, all files in /var/www/NNTmux are now 777 , still cannot login

**Comment by gjm76** [comment]
ok weirdly its now ok in edge and firefox but not chrome.

this is the error i get when i try and add indexer to nzbhydra
The connection to the indexer failed: Error while communicating with indexer nzb.life. Server returned: java.io.IOException: URL call to http://nzb.life/api?apikey=7615c1691e8d81e1e70066e453a86f3f&t=search returned 404: Not Found

**Comment by DariusIII** [comment]
You are using the wrong URl for api, that is why you have issues.

Try this one, but i see you have 500 errors: http://nzb.life/api/v1/api?t=caps

Check your apache/nginx error log to see why it happens, but my guess is permissions again.

**Comment by gjm76** [comment]
I will look in a bit , noticed i got a email when i regged new user even tho it error 500 when created one, verfied account but now no permission to view any page apart from other releases?

 get this


Acess denied! You're permissions and/or role do not allow you to access this page

happens on every user role except admin, have checked the user permisions in admin and all can view everything.

**Comment by gjm76** [comment]
and i get nothing in nginx error log. Feel like my install really doesnt work, which is weird as followed the ubuntu guide completely, substituting php7.3 for 7.1.  Apart from whats in the guide was anything else needed as its soooo broken

**Comment by DariusIII** [comment]
Php 7.1 is not supported, btw.
7.2 is minimum version supported.

**Comment by DariusIII** [comment]
Also, please do not mix issues. Open new issue for each problem you have.
BTW, every user has to edit his profile and adjust view part, to enable
categories he can see.

**Comment by gjm76** [comment]
ok sorry i meant php 7.2.  weirdly on the email issue ive noticed that registering a new account doesnt send the email just a error 500 but in the admin panel if i resend email verification it sends it
